inherit_from: .rubocop_todo.yml
Rails:
  Enabled: true
Metrics/BlockLength:
    Exclude:
    - 'spec/**/*'
    - 'config/environments/development.rb'
Rails/ApplicationRecord:
  Enabled: false
Rails/Exit:
  Exclude:
    - 'lib/**/*.rake'
    - 'lib/postman.rb'
# The default created_at and updated_at timestamps can be a little confusing
# when we have similar data coming from the remote lims.
Rails/CreateTableWithTimestamps:
  Enabled: false
