CREATE TABLE `iseq_external_product_components` (
  `id_iseq_ext_pr_components_tmp` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Internal to this database id, value can change',
  `id_iseq_product_ext` char(64) COLLATE utf8_unicode_ci NOT NULL COMMENT 'id (digest) for the external product composition',
  `id_iseq_product` char(64) COLLATE utf8_unicode_ci NOT NULL COMMENT 'id (digest) for one of the products components',
  `num_components` tinyint(3) unsigned NOT NULL COMMENT 'Number of component products for this product',
  `component_index` tinyint(3) unsigned NOT NULL COMMENT 'Unique component index within all components of this product, a value from 1 to the value of num_components column for this product',
  PRIMARY KEY (`id_iseq_ext_pr_components_tmp`),
  UNIQUE KEY `iseq_ext_pr_comp_unique` (`id_iseq_product`,`id_iseq_product_ext`),
  KEY `iseq_ext_pr_comp_pr_comp_fk` (`id_iseq_product_ext`),
  KEY `iseq_ext_pr_comp_ncomp` (`num_components`,`id_iseq_product`),
  KEY `iseq_ext_pr_comp_compi` (`component_index`,`num_components`),
  CONSTRAINT `id_iseq_product_ext_digest_fk` FOREIGN KEY (`id_iseq_product_ext`) REFERENCES `iseq_external_product_metrics` (`id_iseq_product`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=426556 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Table linking iseq_external_product_metrics table products to components in the iseq_product_metrics table';

CREATE TABLE `iseq_external_product_metrics` (
  `id_iseq_ext_pr_metrics_tmp` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Internal to this database id, value can change',
  `created` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Datetime this record was created',
  `last_changed` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Datetime this record was created or changed',
  `supplier_sample_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Sample name given by the supplier, as recorded by WSI',
  `plate_barcode` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Stock plate barcode, as recorded by WSI',
  `library_id` int(11) DEFAULT NULL COMMENT 'WSI library identifier',
  `file_name` varchar(300) NOT NULL COMMENT 'Comma-delimitered alphabetically sorted list of file names, which unambigiously define WSI sources of data',
  `file_path` varchar(760) NOT NULL COMMENT 'Comma-delimitered alphabetically sorted list of full external file paths for the files in file_names column as uploaded by WSI',
  `md5_staging` char(32) DEFAULT NULL COMMENT 'WSI validation hex MD5, not set for multiple source files',
  `manifest_upload_status` char(15) DEFAULT NULL COMMENT 'WSI manifest upload status, one of "IN PROGRESS", "DONE", "FAIL", not set for multiple source files',
  `manifest_upload_status_change_date` datetime DEFAULT NULL COMMENT 'Date the status of manifest upload is changed by WSI',
  `id_run` int(10) unsigned DEFAULT NULL COMMENT 'NPG run identifier, defined where the product corresponds to a single line',
  `id_iseq_product` char(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'product id',
  `iseq_composition_tmp` varchar(600) DEFAULT NULL COMMENT 'JSON representation of the composition object, the column might be deleted in future',
  `id_archive_product` char(64) DEFAULT NULL COMMENT 'Archive ID for data product',
  `destination` varchar(15) DEFAULT 'UKBMP' COMMENT 'Data destination, from 20200323 defaults to "UKBMP"',
  `processing_status` char(15) DEFAULT NULL COMMENT 'Overall status of the product, one of "PASS", "HOLD", "INSUFFICIENT", "FAIL"',
  `qc_overall_assessment` char(4) DEFAULT NULL COMMENT 'State of the product after phase 3 of processing, one of "PASS" or "FAIL"',
  `qc_status` char(15) DEFAULT NULL COMMENT 'State of the product after phase 2 of processing, one of "PASS", "HOLD", "INSUFFICIENT", "FAIL"',
  `sequencing_start_date` date DEFAULT NULL COMMENT 'Sequencing start date obtained from the CRAM file header, not set for multiple source files',
  `upload_date` date DEFAULT NULL COMMENT 'Upload date, not set for multiple source files',
  `md5_validation_date` date DEFAULT NULL COMMENT 'Date of MD5 validation, not set for multiple source files',
  `processing_start_date` date DEFAULT NULL COMMENT 'Processing start date',
  `analysis_start_date` date DEFAULT NULL,
  `phase2_end_date` datetime DEFAULT NULL COMMENT 'Date the phase 2 analysis finished for this product',
  `analysis_end_date` date DEFAULT NULL,
  `archival_date` date DEFAULT NULL COMMENT 'Date made available or pushed to archive service',
  `archive_confirmation_date` date DEFAULT NULL COMMENT 'Date of confirmation of integrity of data product by archive service',
  `md5` char(32) DEFAULT NULL COMMENT 'External validation hex MD5, not set for multiple source files',
  `md5_validation` char(4) DEFAULT NULL COMMENT 'Outcome of MD5 validation as "PASS" or "FAIL", not set for multiple source files',
  `format_validation` char(4) DEFAULT NULL COMMENT 'Outcome of format validation as "PASS" or "FAIL", not set for multiple source files',
  `upload_status` char(4) DEFAULT NULL COMMENT 'Upload status as "PASS" or "FAIL", "PASS" if both MD5 and format validation are "PASS", not set for multiple source files',
  `instrument_id` varchar(256) DEFAULT NULL COMMENT 'Comma separated sorted list of instrument IDs obtained from the CRAM file header(s)',
  `flowcell_id` varchar(256) DEFAULT NULL COMMENT 'Comma separated sorted list of flowcell IDs obtained from the CRAM file header(s)',
  `annotation` varchar(15) DEFAULT NULL COMMENT 'Annotation regarding data provenance, i.e. is sequence data from first pass, re-run, top-up, etc.',
  `min_read_length` tinyint(3) unsigned DEFAULT NULL COMMENT 'Minimum read length observed in the data file',
  `target_autosome_coverage_threshold` int(3) unsigned DEFAULT '15' COMMENT 'Target autosome coverage threshold, defaults to 15',
  `target_autosome_gt_coverage_threshold` float DEFAULT NULL COMMENT 'Coverage percent at >= target_autosome_coverage_threshold X as a fraction',
  `target_autosome_gt_coverage_threshold_assessment` char(4) DEFAULT NULL COMMENT '"PASS" if target_autosome_percent_gt_coverage_threshold > 95%, "FAIL" otherwise',
  `verify_bam_id_score` float unsigned DEFAULT NULL COMMENT 'FREEMIX value of sample contamination levels as a fraction',
  `verify_bam_id_score_assessment` char(4) DEFAULT NULL COMMENT '"PASS" if verify_bam_id_score > 0.01, "FAIL" otherwise',
  `double_error_fraction` float unsigned DEFAULT NULL COMMENT 'Fraction of marker pairs with two read pairs evidencing parity and non-parity, may only be calculated if 1% <= verify_bam_id_score < 5%',
  `contamination_assessment` char(4) DEFAULT NULL COMMENT '"PASS" or "FAIL" based on verify_bam_id_score_assessment and double_error_fraction < 0.2%',
  `yield_whole_genome` float unsigned DEFAULT NULL COMMENT 'Sequence data quantity (Gb) excluding duplicate reads, adaptors, overlapping bases from reads on the same fragment, soft-clipped bases',
  `yield` float unsigned DEFAULT NULL COMMENT 'Sequence data quantity (Gb) excluding duplicate reads, adaptors, overlapping bases from reads on the same fragment, soft-clipped bases, non-N autosome only',
  `yield_q20` bigint(20) unsigned DEFAULT NULL COMMENT 'Yield in bases at or above Q20 filtered in the same way as the yield column values',
  `yield_q30` bigint(20) unsigned DEFAULT NULL COMMENT 'Yield in bases at or above Q30 filtered in the same way as the yield column values',
  `num_reads` bigint(20) unsigned DEFAULT NULL COMMENT 'Number of reads filtered in the same way as the yield column values',
  `gc_fraction_forward_read` float unsigned DEFAULT NULL,
  `gc_fraction_reverse_read` float unsigned DEFAULT NULL,
  `adapter_contamination` varchar(255) DEFAULT NULL COMMENT 'The maximum over adapters and cycles in reads/fragments as a fraction per file and RG. Values for first and second reads separated with ",", and values for individual files separated with "/". e.g. "0.1/0.1/0.1/0.1,0.1/0.1/0.1/0.1"',
  `adapter_contamination_assessment` varchar(255) DEFAULT NULL COMMENT '"PASS", "WARN", "FAIL" per read and file. Multiple values are represented as forward slash-separated array of strings with a comma separating entries for paired-end 1 and 2 reads e.g. "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `pre_adapter_min_total_qscore` tinyint(3) unsigned DEFAULT NULL COMMENT 'Minimum of TOTAL_QSCORE values in PreAdapter report from CollectSequencingArtifactMetrics',
  `ref_bias_min_total_qscore` tinyint(3) unsigned DEFAULT NULL COMMENT 'Minimum of TOTAL_QSCORE values in BaitBias report from CollectSequencingArtifactMetrics',
  `target_proper_pair_mapped_reads_fraction` float unsigned DEFAULT NULL COMMENT 'Fraction of properly paired mapped reads filtered in the same way as the yield column values',
  `target_proper_pair_mapped_reads_assessment` char(4) DEFAULT NULL COMMENT '"PASS" if target_proper_pair_mapped_reads_fraction > 0.95, "FAIL" otherwise',
  `insert_size_mean` float unsigned DEFAULT NULL,
  `insert_size_std` float unsigned DEFAULT NULL,
  `sequence_error_rate` float unsigned DEFAULT NULL COMMENT 'Reported by samtools, as a fraction',
  `basic_statistics_assessement` varchar(255) DEFAULT NULL COMMENT 'FastQC "PASS", "WARN", "FAIL" per input file. Array of strings separated by "/", with a "," separating entries for paired-end 1 and 2 reads. e.g. Four RG "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `overrepresented_sequences_assessement` varchar(255) DEFAULT NULL COMMENT 'FastQC "PASS", "WARN", "FAIL" per input file. Array of strings separated by "/", with a "," separating entries for paired-end 1 and 2 reads. e.g. Four RG "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `n_content_per_base_assessement` varchar(255) DEFAULT NULL COMMENT 'FastQC "PASS", "WARN", "FAIL" per input file. Array of strings separated by "/", with a "," separating entries for paired-end 1 and 2 reads. e.g. Four RG "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `sequence_content_per_base_assessement` varchar(255) DEFAULT NULL COMMENT 'FastQC "PASS", "WARN", "FAIL" per input file. Array of strings separated by "/", with a "," separating entries for paired-end 1 and 2 reads. e.g. Four RG "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `sequence_quality_per_base_assessement` varchar(255) DEFAULT NULL COMMENT 'FastQC "PASS", "WARN", "FAIL" per input file. Array of strings separated by "/", with a "," separating entries for paired-end 1 and 2 reads. e.g. Four RG "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `gc_content_per_sequence_assessement` varchar(255) DEFAULT NULL COMMENT 'FastQC "PASS", "WARN", "FAIL" per input file. Array of strings separated by "/", with a "," separating entries for paired-end 1 and 2 reads. e.g. Four RG "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `quality_scores_per_sequence_assessement` varchar(255) DEFAULT NULL COMMENT 'FastQC "PASS", "WARN", "FAIL" per input file. Array of strings separated by "/", with a "," separating entries for paired-end 1 and 2 reads. e.g. Four RG "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `sequence_duplication_levels_assessement` varchar(255) DEFAULT NULL COMMENT 'FastQC "PASS", "WARN", "FAIL" per input file. Array of strings separated by "/", with a "," separating entries for paired-end 1 and 2 reads. e.g. Four RG "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `sequence_length_distribution_assessement` varchar(255) DEFAULT NULL COMMENT 'FastQC "PASS", "WARN", "FAIL" per input file. Array of strings separated by "/", with a "," separating entries for paired-end 1 and 2 reads. e.g. Four RG "PASS/PASS/WARN/PASS,PASS/PASS/WARN/PASS"',
  `FastQC_overall_assessment` char(4) DEFAULT NULL COMMENT 'FastQC "PASS" or "FAIL"',
  `nrd` float unsigned DEFAULT NULL COMMENT 'Sample discordance levels at non-reference genotypes as a fraction',
  `nrd_assessment` char(4) DEFAULT NULL COMMENT '"PASS" based on nrd_persent < 2% or "FAIL" or "NA" if genotyping data not available for this sample',
  `sex_reported` char(6) DEFAULT NULL COMMENT 'Sex as reported by sample supplier',
  `sex_computed` char(6) DEFAULT NULL COMMENT 'Genetic sex as identified by sequence data',
  PRIMARY KEY (`id_iseq_ext_pr_metrics_tmp`),
  UNIQUE KEY `iseq_ext_pr_file_path` (`file_path`),
  KEY `iseq_ext_pr_manifest_status` (`manifest_upload_status`),
  KEY `iseq_ext_pr_prstatus` (`processing_status`),
  KEY `iseq_ext_pr_qc` (`qc_overall_assessment`),
  KEY `iseq_ext_pr_instrument` (`instrument_id`),
  KEY `iseq_ext_pr_flowcell` (`flowcell_id`),
  KEY `iseq_ext_pr_fname` (`file_name`),
  KEY `iseq_ext_pr_lib_id` (`library_id`),
  KEY `iseq_ext_pr_sample_name` (`supplier_sample_name`),
  KEY `iseq_ext_pr_plate_bc` (`plate_barcode`),
  KEY `iseq_ext_pr_id_product` (`id_iseq_product`),
  KEY `iseq_ext_pr_id_run` (`id_run`)
) ENGINE=InnoDB AUTO_INCREMENT=111260 DEFAULT CHARSET=latin1 COMMENT='Externally computed metrics for data sequenced at WSI';

CREATE TABLE `iseq_flowcell` (
  `id_iseq_flowcell_tmp` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Internal to this database id, value can change',
  `last_updated` datetime NOT NULL COMMENT 'Timestamp of last update',
  `recorded_at` datetime NOT NULL COMMENT 'Timestamp of warehouse update',
  `id_sample_tmp` int(10) unsigned NOT NULL COMMENT 'Sample id, see "sample.id_sample_tmp"',
  `id_study_tmp` int(10) unsigned DEFAULT NULL COMMENT 'Study id, see "study.id_study_tmp"',
  `cost_code` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Valid WTSI cost code',
  `is_r_and_d` tinyint(1) DEFAULT '0' COMMENT 'A boolean flag derived from cost code, flags RandD',
  `id_lims` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'LIM system identifier, e.g. CLARITY-GCLP, SEQSCAPE',
  `priority` smallint(2) unsigned DEFAULT '1' COMMENT 'Priority',
  `manual_qc` tinyint(1) DEFAULT NULL COMMENT 'Manual QC decision, NULL for unknown',
  `external_release` tinyint(1) DEFAULT NULL COMMENT 'Defaults to manual qc value; can be changed by the user later',
  `flowcell_barcode` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Manufacturer flowcell barcode or other identifier',
  `id_flowcell_lims` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'LIMs-specific flowcell id, batch_id for Sequencescape',
  `position` smallint(2) unsigned NOT NULL COMMENT 'Flowcell lane number',
  `entity_type` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lane type: library, pool, library_control, library_indexed, library_indexed_spike',
  `entity_id_lims` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Most specific LIMs identifier associated with this lane or plex or spike',
  `tag_index` smallint(5) unsigned DEFAULT NULL COMMENT 'Tag index, NULL if lane is not a pool',
  `tag_sequence` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Tag sequence',
  `tag_set_id_lims` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'LIMs-specific identifier of the tag set',
  `tag_set_name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'WTSI-wide tag set name',
  `tag_identifier` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'The position of tag within the tag group',
  `tag2_sequence` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Tag sequence for tag 2',
  `tag2_set_id_lims` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'LIMs-specific identifier of the tag set for tag 2',
  `tag2_set_name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'WTSI-wide tag set name for tag 2',
  `tag2_identifier` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'The position of tag2 within the tag group',
  `is_spiked` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Boolean flag indicating presence of a spike',
  `pipeline_id_lims` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'LIMs-specific pipeline identifier that unambiguously defines library type',
  `bait_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'WTSI-wide name that uniquely identifies a bait set',
  `requested_insert_size_from` int(5) unsigned DEFAULT NULL COMMENT 'Requested insert size min value',
  `requested_insert_size_to` int(5) unsigned DEFAULT NULL COMMENT 'Requested insert size max value',
  `forward_read_length` smallint(4) unsigned DEFAULT NULL COMMENT 'Requested forward read length, bp',
  `reverse_read_length` smallint(4) unsigned DEFAULT NULL COMMENT 'Requested reverse read length, bp',
  `id_pool_lims` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Most specific LIMs identifier associated with the pool',
  `legacy_library_id` int(11) DEFAULT NULL COMMENT 'Legacy library_id for backwards compatibility.',
  `id_library_lims` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Earliest LIMs identifier associated with library creation',
  `team` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'The team responsible for creating the flowcell',
  `purpose` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Describes the reason the sequencing was conducted. Eg. Standard, QC, Control',
  `suboptimal` tinyint(1) DEFAULT NULL COMMENT 'Indicates that a sample has failed a QC step during processing',
  `primer_panel` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Primer Panel name',
  `spiked_phix_barcode` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Barcode of the PhiX tube added to the lane',
  `spiked_phix_percentage` float DEFAULT NULL COMMENT 'Percentage PhiX tube spiked in the pool in terms of molar concentration',
  `loading_concentration` float DEFAULT NULL COMMENT 'Final instrument loading concentration (pM)',
  `workflow` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Workflow used when processing the flowcell',
  PRIMARY KEY (`id_iseq_flowcell_tmp`),
  UNIQUE KEY `index_iseq_flowcell_id_flowcell_lims_position_tag_index_id_lims` (`id_flowcell_lims`,`position`,`tag_index`,`id_lims`),
  KEY `iseq_flowcell_id_lims_id_flowcell_lims_index` (`id_lims`,`id_flowcell_lims`),
  KEY `iseq_flowcell_sample_fk` (`id_sample_tmp`),
  KEY `iseq_flowcell_study_fk` (`id_study_tmp`),
  KEY `index_iseq_flowcell_on_id_pool_lims` (`id_pool_lims`),
  KEY `index_iseq_flowcell_on_id_library_lims` (`id_library_lims`),
  KEY `index_iseqflowcell__id_flowcell_lims__position__tag_index` (`id_flowcell_lims`,`position`,`tag_index`),
  KEY `index_iseqflowcell__flowcell_barcode__position__tag_index` (`flowcell_barcode`,`position`,`tag_index`),
  KEY `index_iseq_flowcell_legacy_library_id` (`legacy_library_id`),
  CONSTRAINT `iseq_flowcell_sample_fk` FOREIGN KEY (`id_sample_tmp`) REFERENCES `sample` (`id_sample_tmp`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iseq_flowcell_study_fk` FOREIGN KEY (`id_study_tmp`) REFERENCES `study` (`id_study_tmp`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7871154 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `iseq_heron_product_metrics` (
  `id_iseq_hrpr_metrics_tmp` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Internal to this database id, value can change',
  `created` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Datetime this record was created',
  `last_changed` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Datetime this record was created or changed',
  `id_run` int(10) unsigned DEFAULT NULL COMMENT 'Run id',
  `id_iseq_product` char(64) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Product id, a foreign key into iseq_product_metrics table',
  `supplier_sample_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Sample name given by the supplier, as recorded by WSI',
  `pp_name` varchar(40) COLLATE utf8_unicode_ci DEFAULT 'ncov2019-artic-nf' COMMENT 'The name of the pipeline that produced the QC metric',
  `pp_version` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'The version of the pipeline specified in the pp_name column',
  `artic_qc_outcome` char(15) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Artic pipeline QC outcome, "TRUE", "FALSE" or a NULL value',
  `climb_upload` datetime DEFAULT NULL COMMENT 'Datetime files for this sample were uploaded to CLIMB',
  `cog_sample_meta` tinyint(1) unsigned DEFAULT NULL COMMENT 'A Boolean flag to mark sample metadata upload to COG',
  `path_root` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'The uploaded files path root for the entity',
  `pct_N_bases` float DEFAULT NULL COMMENT 'Percent of N bases',
  `pct_covered_bases` float DEFAULT NULL COMMENT 'Percent of covered bases',
  `longest_no_N_run` smallint(5) unsigned DEFAULT NULL COMMENT 'Longest consensus data stretch without N',
  `num_aligned_reads` bigint(20) unsigned DEFAULT NULL COMMENT 'Number of aligned filtered reads',
  PRIMARY KEY (`id_iseq_hrpr_metrics_tmp`),
  UNIQUE KEY `iseq_hrm_digest_unq` (`id_iseq_product`),
  KEY `iseq_hrm_ssn` (`supplier_sample_name`),
  KEY `iseq_hrm_idrun` (`id_run`),
  KEY `iseq_hrm_ppver` (`pp_version`)
) ENGINE=InnoDB AUTO_INCREMENT=173555 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Heron project additional metrics';

CREATE TABLE `iseq_product_ampliconstats` (
  `id_iseq_pr_astats_tmp` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Internal to this database id, value can change',
  `created` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Datetime this record was created',
  `last_changed` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Datetime this record was created or changed',
  `id_iseq_product` char(64) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Product id, a foreign key into iseq_product_metrics table',
  `primer_panel` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'A string uniquely identifying the primer panel',
  `primer_panel_num_amplicons` smallint(5) unsigned NOT NULL COMMENT 'Total number of amplicons in the primer panel',
  `amplicon_index` smallint(5) unsigned NOT NULL COMMENT 'Amplicon index (position) in the primer panel, from 1 to the value of primer_panel_num_amplicons',
  `pp_name` varchar(40) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Name of the portable pipeline that generated the data',
  `pp_version` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Version of the portable pipeline and/or samtools that generated the data',
  `metric_FPCOV_1` decimal(5,2) DEFAULT NULL COMMENT 'Coverage percent at depth 1',
  `metric_FPCOV_10` decimal(5,2) DEFAULT NULL COMMENT 'Coverage percent at depth 10',
  `metric_FPCOV_20` decimal(5,2) DEFAULT NULL COMMENT 'Coverage percent at depth 20',
  `metric_FPCOV_100` decimal(5,2) DEFAULT NULL COMMENT 'Coverage percent at depth 100',
  `metric_FREADS` int(10) unsigned DEFAULT NULL COMMENT 'Number of aligned filtered reads',
  PRIMARY KEY (`id_iseq_pr_astats_tmp`),
  UNIQUE KEY `iseq_hrm_digest_unq` (`id_iseq_product`,`primer_panel`,`amplicon_index`),
  KEY `iseq_pastats_amplicon` (`primer_panel_num_amplicons`,`amplicon_index`),
  CONSTRAINT `iseq_pastats_prm_fk` FOREIGN KEY (`id_iseq_product`) REFERENCES `iseq_product_metrics` (`id_iseq_product`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=8924763 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Some of per sample per amplicon metrics generated by samtools ampliconstats';

CREATE TABLE `iseq_product_components` (
  `id_iseq_pr_components_tmp` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Internal to this database id, value can change',
  `id_iseq_pr_tmp` bigint(20) unsigned NOT NULL COMMENT 'iseq_product_metrics table row id for the product',
  `id_iseq_pr_component_tmp` bigint(20) unsigned NOT NULL COMMENT 'iseq_product_metrics table row id for one of this product''s components',
  `num_components` tinyint(3) unsigned NOT NULL COMMENT 'Number of component products for this product',
  `component_index` tinyint(3) unsigned NOT NULL COMMENT 'Unique component index within all components of this product, \na value from 1 to the value of num_components column for this product',
  PRIMARY KEY (`id_iseq_pr_components_tmp`),
  UNIQUE KEY `iseq_pr_comp_unique` (`id_iseq_pr_tmp`,`id_iseq_pr_component_tmp`),
  KEY `iseq_pr_comp_pr_comp_fk` (`id_iseq_pr_component_tmp`),
  KEY `iseq_pr_comp_ncomp` (`num_components`,`id_iseq_pr_tmp`),
  KEY `iseq_pr_comp_compi` (`component_index`,`num_components`),
  CONSTRAINT `iseq_pr_comp_pr_comp_fk` FOREIGN KEY (`id_iseq_pr_component_tmp`) REFERENCES `iseq_product_metrics` (`id_iseq_pr_metrics_tmp`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iseq_pr_comp_pr_fk` FOREIGN KEY (`id_iseq_pr_tmp`) REFERENCES `iseq_product_metrics` (`id_iseq_pr_metrics_tmp`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4716250 DEFAULT CHARSET=utf8;

CREATE TABLE `iseq_product_metrics` (
  `id_iseq_pr_metrics_tmp` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Internal to this database id, value can change',
  `id_iseq_product` char(64) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Product id',
  `last_changed` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Date this record was created or changed',
  `id_iseq_flowcell_tmp` int(10) unsigned DEFAULT NULL COMMENT 'Flowcell id, see "iseq_flowcell.id_iseq_flowcell_tmp"',
  `id_run` int(10) unsigned DEFAULT NULL COMMENT 'NPG run identifier',
  `position` smallint(2) unsigned DEFAULT NULL COMMENT 'Flowcell lane number',
  `tag_index` smallint(5) unsigned DEFAULT NULL COMMENT 'Tag index, NULL if lane is not a pool',
  `iseq_composition_tmp` varchar(600) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'JSON representation of the composition object, the column might be deleted in future',
  `qc_seq` tinyint(1) DEFAULT NULL COMMENT 'Sequencing lane level QC outcome, a result of either manual or automatic assessment by core',
  `qc_lib` tinyint(1) DEFAULT NULL COMMENT 'Library QC outcome, a result of either manual or automatic assessment by core',
  `qc_user` tinyint(1) DEFAULT NULL COMMENT 'Library QC outcome according to the data user criteria, a result of either manual or automatic assessment',
  `qc` tinyint(1) DEFAULT NULL COMMENT 'Overall QC assessment outcome, a logical product (conjunction) of qc_seq and qc_lib values, defaults to the qc_seq value when qc_lib is not defined',
  `tag_sequence4deplexing` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Tag sequence used for deplexing the lane, common suffix might have been truncated',
  `actual_forward_read_length` smallint(4) unsigned DEFAULT NULL COMMENT 'Actual forward read length, bp',
  `actual_reverse_read_length` smallint(4) unsigned DEFAULT NULL COMMENT 'Actual reverse read length, bp',
  `indexing_read_length` smallint(2) unsigned DEFAULT NULL COMMENT 'Indexing read length, bp',
  `tag_decode_percent` float(5,2) unsigned DEFAULT NULL,
  `tag_decode_count` int(10) unsigned DEFAULT NULL,
  `insert_size_quartile1` smallint(5) unsigned DEFAULT NULL,
  `insert_size_quartile3` smallint(5) unsigned DEFAULT NULL,
  `insert_size_median` smallint(5) unsigned DEFAULT NULL,
  `insert_size_num_modes` smallint(4) unsigned DEFAULT NULL,
  `insert_size_normal_fit_confidence` float(3,2) unsigned DEFAULT NULL,
  `gc_percent_forward_read` float(5,2) unsigned DEFAULT NULL,
  `gc_percent_reverse_read` float(5,2) unsigned DEFAULT NULL,
  `sequence_mismatch_percent_forward_read` float(4,2) unsigned DEFAULT NULL,
  `sequence_mismatch_percent_reverse_read` float(4,2) unsigned DEFAULT NULL,
  `adapters_percent_forward_read` float(5,2) unsigned DEFAULT NULL,
  `adapters_percent_reverse_read` float(5,2) unsigned DEFAULT NULL,
  `ref_match1_name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ref_match1_percent` float(5,2) DEFAULT NULL,
  `ref_match2_name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ref_match2_percent` float(5,2) DEFAULT NULL,
  `q20_yield_kb_forward_read` int(10) unsigned DEFAULT NULL,
  `q20_yield_kb_reverse_read` int(10) unsigned DEFAULT NULL,
  `q30_yield_kb_forward_read` int(10) unsigned DEFAULT NULL,
  `q30_yield_kb_reverse_read` int(10) unsigned DEFAULT NULL,
  `q40_yield_kb_forward_read` int(10) unsigned DEFAULT NULL,
  `q40_yield_kb_reverse_read` int(10) unsigned DEFAULT NULL,
  `num_reads` bigint(20) unsigned DEFAULT NULL,
  `percent_mapped` float(5,2) DEFAULT NULL,
  `percent_duplicate` float(5,2) DEFAULT NULL,
  `chimeric_reads_percent` float(5,2) unsigned DEFAULT NULL COMMENT 'mate_mapped_defferent_chr_5 as percentage of all',
  `human_percent_mapped` float(5,2) DEFAULT NULL,
  `human_percent_duplicate` float(5,2) DEFAULT NULL,
  `genotype_sample_name_match` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `genotype_sample_name_relaxed_match` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `genotype_mean_depth` float(7,2) DEFAULT NULL,
  `mean_bait_coverage` float(8,2) unsigned DEFAULT NULL,
  `on_bait_percent` float(5,2) unsigned DEFAULT NULL,
  `on_or_near_bait_percent` float(5,2) unsigned DEFAULT NULL,
  `verify_bam_id_average_depth` float(11,2) unsigned DEFAULT NULL,
  `verify_bam_id_score` float(6,5) unsigned DEFAULT NULL,
  `verify_bam_id_snp_count` int(10) unsigned DEFAULT NULL,
  `rna_exonic_rate` float unsigned DEFAULT NULL COMMENT 'Exonic Rate is the fraction mapping within exons',
  `rna_percent_end_2_reads_sense` float unsigned DEFAULT NULL COMMENT 'Percentage of intragenic End 2 reads that were sequenced in the sense direction.',
  `rna_rrna_rate` float unsigned DEFAULT NULL COMMENT 'rRNA Rate is per total reads',
  `rna_genes_detected` int(10) unsigned DEFAULT NULL COMMENT 'Number of genes detected with at least 5 reads.',
  `rna_norm_3_prime_coverage` float unsigned DEFAULT NULL COMMENT '3 prime n-based normalization: n is the transcript length at that end; norm is the ratio between the coverage at the 3 prime end and the average coverage of the full transcript, averaged over all transcripts',
  `rna_norm_5_prime_coverage` float unsigned DEFAULT NULL COMMENT '5 prime n-based normalization: n is the transcript length at that end; norm is the ratio between the coverage at the 5 prime end and the average coverage of the full transcript, averaged over all transcripts',
  `rna_intronic_rate` float unsigned DEFAULT NULL COMMENT 'Intronic rate is the fraction mapping within introns',
  `rna_transcripts_detected` int(10) unsigned DEFAULT NULL COMMENT 'Number of transcripts detected with at least 5 reads',
  `rna_globin_percent_tpm` float unsigned DEFAULT NULL COMMENT 'Percentage of globin genes TPM (transcripts per million) detected',
  `rna_mitochondrial_percent_tpm` float unsigned DEFAULT NULL COMMENT 'Percentage of mitochondrial genes TPM (transcripts per million) detected',
  `gbs_call_rate` float unsigned DEFAULT NULL COMMENT 'The GbS call rate is the fraction of loci called on the relevant primer panel',
  `gbs_pass_rate` float unsigned DEFAULT NULL COMMENT 'The GbS pass rate is the fraction of loci called and passing filters on the relevant primer panel',
  `nrd_percent` float(5,2) DEFAULT NULL COMMENT 'Percent of non-reference discordance',
  `target_filter` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Filter used to produce the target stats file',
  `target_length` bigint(12) unsigned DEFAULT NULL COMMENT 'The total length of the target regions',
  `target_mapped_reads` bigint(20) unsigned DEFAULT NULL COMMENT 'The number of mapped reads passing the target filter',
  `target_proper_pair_mapped_reads` bigint(20) unsigned DEFAULT NULL COMMENT 'The number of proper pair mapped reads passing the target filter',
  `target_mapped_bases` bigint(20) unsigned DEFAULT NULL COMMENT 'The number of mapped bases passing the target filter',
  `target_coverage_threshold` int(4) DEFAULT NULL COMMENT 'The coverage threshold used in the target perc target greater than depth calculation',
  `target_percent_gt_coverage_threshold` float(5,2) DEFAULT NULL COMMENT 'The percentage of the target covered at greater than the depth specified',
  `target_autosome_coverage_threshold` int(4) DEFAULT NULL COMMENT 'The coverage threshold used in the perc target autosome greater than depth calculation',
  `target_autosome_percent_gt_coverage_threshold` float(5,2) DEFAULT NULL COMMENT 'The percentage of the target autosome covered at greater than the depth specified',
  PRIMARY KEY (`id_iseq_pr_metrics_tmp`),
  UNIQUE KEY `iseq_pr_metrics_product_unique` (`id_iseq_product`),
  KEY `iseq_pm_fcid_run_pos_tag_index` (`id_run`,`position`,`tag_index`),
  KEY `iseq_pr_metrics_flc_fk` (`id_iseq_flowcell_tmp`),
  CONSTRAINT `iseq_pr_metrics_flc_fk` FOREIGN KEY (`id_iseq_flowcell_tmp`) REFERENCES `iseq_flowcell` (`id_iseq_flowcell_tmp`) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT `iseq_pr_metrics_lm_fk` FOREIGN KEY (`id_run`, `position`) REFERENCES `iseq_run_lane_metrics` (`id_run`, `position`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2104685726 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `iseq_run_lane_metrics` (
  `flowcell_barcode` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Manufacturer flowcell barcode or other identifier as recorded by NPG',
  `id_run` int(10) unsigned NOT NULL COMMENT 'NPG run identifier',
  `position` smallint(2) unsigned NOT NULL COMMENT 'Flowcell lane number',
  `last_changed` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Date this record was created or changed',
  `qc_seq` tinyint(1) DEFAULT NULL COMMENT 'Sequencing lane level QC outcome, a result of either manual or automatic assessment by core',
  `instrument_name` char(32) COLLATE utf8_unicode_ci DEFAULT NULL,
  `instrument_external_name` char(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Name assigned to the instrument by the manufacturer',
  `instrument_model` char(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `instrument_side` char(1) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Illumina instrument side (A or B), if appropriate',
  `workflow_type` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Illumina instrument workflow type',
  `paired_read` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `cycles` int(4) unsigned NOT NULL,
  `cancelled` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Boolen flag to indicate whether the run was cancelled',
  `run_pending` datetime DEFAULT NULL COMMENT 'Timestamp of run pending status',
  `run_complete` datetime DEFAULT NULL COMMENT 'Timestamp of run complete status',
  `qc_complete` datetime DEFAULT NULL COMMENT 'Timestamp of qc complete status',
  `pf_cluster_count` bigint(20) unsigned DEFAULT NULL,
  `raw_cluster_count` bigint(20) unsigned DEFAULT NULL,
  `raw_cluster_density` double(12,3) unsigned DEFAULT NULL,
  `pf_cluster_density` double(12,3) unsigned DEFAULT NULL,
  `pf_bases` bigint(20) unsigned DEFAULT NULL,
  `q20_yield_kb_forward_read` int(10) unsigned DEFAULT NULL,
  `q20_yield_kb_reverse_read` int(10) unsigned DEFAULT NULL,
  `q30_yield_kb_forward_read` int(10) unsigned DEFAULT NULL,
  `q30_yield_kb_reverse_read` int(10) unsigned DEFAULT NULL,
  `q40_yield_kb_forward_read` int(10) unsigned DEFAULT NULL,
  `q40_yield_kb_reverse_read` int(10) unsigned DEFAULT NULL,
  `tags_decode_percent` float(5,2) unsigned DEFAULT NULL,
  `tags_decode_cv` float(6,2) unsigned DEFAULT NULL,
  `unexpected_tags_percent` float(5,2) unsigned DEFAULT NULL COMMENT 'tag0_perfect_match_reads as a percentage of total_lane_reads',
  `tag_hops_percent` float unsigned DEFAULT NULL COMMENT 'Percentage tag hops for dual index runs',
  `tag_hops_power` float unsigned DEFAULT NULL COMMENT 'Power to detect tag hops for dual index runs',
  `run_priority` tinyint(3) DEFAULT NULL COMMENT 'Sequencing lane level run priority, a result of either manual or default value set by core',
  `interop_cluster_count_total` bigint(20) unsigned DEFAULT NULL COMMENT 'Total cluster count for this lane (derived from Illumina InterOp files)',
  `interop_cluster_count_mean` double unsigned DEFAULT NULL COMMENT 'Total cluster count, mean value over tiles of this lane (derived from Illumina InterOp files)',
  `interop_cluster_count_stdev` double unsigned DEFAULT NULL COMMENT 'Standard deviation value for interop_cluster_count_mean',
  `interop_cluster_count_pf_total` bigint(20) unsigned DEFAULT NULL COMMENT 'Purity-filtered cluster count for this lane (derived from Illumina InterOp files)',
  `interop_cluster_count_pf_mean` double unsigned DEFAULT NULL COMMENT 'Purity-filtered cluster count, mean value over tiles of this lane (derived from Illumina InterOp files)',
  `interop_cluster_count_pf_stdev` double unsigned DEFAULT NULL COMMENT 'Standard deviation value for interop_cluster_count_pf_mean',
  `interop_cluster_density_mean` double unsigned DEFAULT NULL COMMENT 'Cluster density, mean value over tiles of this lane (derived from Illumina InterOp files)',
  `interop_cluster_density_stdev` double unsigned DEFAULT NULL COMMENT 'Standard deviation value for interop_cluster_density_mean',
  `interop_cluster_density_pf_mean` double unsigned DEFAULT NULL COMMENT 'Purity-filtered cluster density, mean value over tiles of this lane (derived from Illumina InterOp files)',
  `interop_cluster_density_pf_stdev` double unsigned DEFAULT NULL COMMENT 'Standard deviation value for interop_cluster_density_pf_mean',
  `interop_cluster_pf_mean` float(5,2) unsigned DEFAULT NULL COMMENT ' Percent of purity-filtered clusters, mean value over tiles of this lane (derived from Illumina InterOp files)',
  `interop_cluster_pf_stdev` float(5,2) unsigned DEFAULT NULL COMMENT 'Standard deviation value for interop_cluster_pf_mean',
  `interop_occupied_mean` float(5,2) unsigned DEFAULT NULL COMMENT 'Percent of occupied flowcell wells, a mean value over tiles of this lane (derived from Illumina InterOp files)',
  `interop_occupied_stdev` float(5,2) unsigned DEFAULT NULL COMMENT 'Standard deviation value for interop_occupied_mean',
  PRIMARY KEY (`id_run`,`position`),
  KEY `iseq_rlmm_id_run_index` (`id_run`),
  KEY `iseq_rlm_cancelled_and_run_pending_index` (`cancelled`,`run_pending`),
  KEY `iseq_rlm_cancelled_and_run_complete_index` (`cancelled`,`run_complete`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `iseq_run_status` (
  `id_run_status` int(11) unsigned NOT NULL,
  `id_run` int(10) unsigned NOT NULL COMMENT 'NPG run identifier',
  `date` datetime NOT NULL COMMENT 'Status timestamp',
  `id_run_status_dict` int(10) unsigned NOT NULL COMMENT 'Status identifier, see iseq_run_status_dict.id_run_status_dict',
  `iscurrent` tinyint(1) NOT NULL COMMENT 'Boolean flag, 1 is the status is current, 0 otherwise',
  PRIMARY KEY (`id_run_status`),
  KEY `iseq_run_status_rsd_fk` (`id_run_status_dict`),
  KEY `id_run_status_id_run` (`id_run`),
  CONSTRAINT `iseq_run_status_rsd_fk` FOREIGN KEY (`id_run_status_dict`) REFERENCES `iseq_run_status_dict` (`id_run_status_dict`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `iseq_run_status_dict` (
  `id_run_status_dict` int(10) unsigned NOT NULL,
  `description` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `iscurrent` tinyint(3) unsigned NOT NULL,
  `temporal_index` smallint(5) unsigned DEFAULT NULL,
  PRIMARY KEY (`id_run_status_dict`),
  KEY `iseq_run_status_dict_description_index` (`description`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
