#!/bin/bash -l

# Usage: worker identity action
# Eg: worker unified_warehouse.production.1 start

PID_DIR='tmp/pids'

function worker_start() {
  echo "Starting Amqp worker"
  bundle exec ./bin/amqp_client start
}

function worker_stop() {
  echo "Stopping Amqp worker"
  bundle exec ./bin/amqp_client stop
}

function worker_restart() {
  worker_stop
  worker_start
}

worker_${2} $1
exit 0
