class AddLighthouseSamples < ActiveRecord::Migration
  def change
    create_table :lighthouse_samples do |t|
      t.string :mongodb_id, comment: 'Auto-generated id from MongoDB'
      t.string :root_sample_id, comment: 'Id for this sample provided by the Lighthouse lab'
      t.string :cog_uk_id, comment: 'Consortium-wide id, generated by Sanger on import to LIMS'
      t.string :rna_id, comment: 'Lighthouse lab-provided id made up of plate barcode and well'
      t.string :plate_barcode, comment: 'Barcode of plate sample arrived in, from rna_id'
      t.string :coordinate, comment: 'Well position from plate sample arrived in, from rna_id'
      t.string :result, comment: 'Covid-19 test result from the Lighthouse lab'
      t.string :date_tested_string, comment: 'When the covid-19 test was carried out by the Lighthouse lab'
      t.datetime :date_tested, comment: 'date_tested_string in date format'
      t.string :source, comment: 'Lighthouse centre that the sample came from'
      t.string :lab_id, comment: 'Id of the lab, within the Lighthouse centre'
      t.datetime :created, comment: 'When the corresponding record was inserted into the MongoDB'
      t.datetime :last_updated, comment: 'When the corresponding record was last updated in MongoDB'
      t.datetime :created_at, comment: 'When this record was inserted' # don't use rails column name?
      t.datetime :updated_at, comment: 'When this record was most last updated' # don't use rails column name?

      t.index [:root_sample_id, :rna_id, :result], unique: true # same uniqueness criteria as in MongoDB
      t.index :mongodb_id, unique: true
      t.index :date_tested # reporting will often be by date tested, so index for faster queries
    end
  end
end

# Example MongoDB record
# {
#   "_id" : ObjectId("5f3a91045019939dc1ac317b"),
#   "Lab ID" : "AP",
#   "RNA ID" : "AP-rna-00110029_F11",
#   "Date Tested" : "2020-04-23 14:40:08 UTC",
#   "RNA-PCR ID" : "CF06CR9S_F11",
#   "Viral Prep ID" : "AP-kfr-00070085_F11",
#   "Root Sample ID" : "GNM00015904",
#   "Result" : "Negative",
#   "source" : "Alderley",
#   "plate_barcode" : "AP-rna-00110029",
#   "coordinate" : "F11",
#   "line_number" : 24,
#   "file_name" : "AP_sanger_report_200423_2214.csv",
#   "file_name_date" : ISODate("2020-04-23T22:14:00Z"),
#   "created_at" : ISODate("2020-05-07T12:51:00Z"),
#   "updated_at" : ISODate("2020-08-17T15:15:32.048Z"),
#   "concat_id" : "GNM00015904 - AP-rna-00110029_F11 - Negative",
#   "migrated_temp" : "Yes"
# }