class AddLighthouseSamples < ActiveRecord::Migration
  def change
    create_table :lighthouse_samples do |t|
      t.string :mongodb_id, comment: 'The auto-generated id from the Lighthouse MongoDB document that corresponds to this record.'
      t.string :root_sample_id, comment: 'Id for this sample provided by the Lighthouse lab.'
      t.string :cog_uk_id, comment: 'Id for this sample generated by Sanger for use by whole COG UK consortium. At time of writing, generated by Baracoda app during Lighthouse Sentinel sample creation process.'
      t.string :rna_id, comment: 'Id provided by the Lighthouse lab, made up of the barcode and well position of the plate the sample arrived in.'
      t.string :plate_barcode, comment: 'Barcode of the plate the sample arrived in, provided by the Lighthouse lab. Extracted from rna_id during Lighthouse import process.'
      t.string :coordinate, comment: 'Well position that the sample occupied on the plate it arrived in. Extracted from rna_id during Lighthouse import process.'
      t.string :result, comment: 'The covid-19 test result from the Lighthouse lab.'
      t.string :date_tested_string, comment: 'The date the covid-19 test was carried out by the Lighthouse lab, as provided by the Lighthouse lab.'
      t.datetime :date_tested, comment: 'The date the covid-19 test was carried out by the Lighthouse lab, converted from a string into a date if possible.'
      t.string :source, comment: 'The Lighthouse centre that the sample came from.'
      t.string :lab_id, 'The ID of the particular lab the sample came from, within the Lighthouse centre, only relevant if it has more than one lab.'
      t.datetime :created, comment: 'When the corresponding record was inserted into the Lighthouse MongoDB.'
      t.datetime :last_updated, comment: 'When the corresponding record was most recently updated in the Lighthouse MongoDB.'
      t.datetime :created_at, comment: 'When this record was inserted.' # don't use rails column name?
      t.datetime :updated_at, comment: 'When this record was most recently updated.' # don't use rails column name?

      t.index [:root_sample_id, :rna_id, :result], unique: true # same uniqueness criteria as in MongoDB
      t.index :mongodb_id, unique: true
      t.index :date_tested # reporting will often be by date tested, so index for faster queries
    end
  end
end

# Example MongoDB record
# {
#   "_id" : ObjectId("5f3a91045019939dc1ac317b"),
#   "Lab ID" : "AP",
#   "RNA ID" : "AP-rna-00110029_F11",
#   "Date Tested" : "2020-04-23 14:40:08 UTC",
#   "RNA-PCR ID" : "CF06CR9S_F11",
#   "Viral Prep ID" : "AP-kfr-00070085_F11",
#   "Root Sample ID" : "GNM00015904",
#   "Result" : "Negative",
#   "source" : "Alderley",
#   "plate_barcode" : "AP-rna-00110029",
#   "coordinate" : "F11",
#   "line_number" : 24,
#   "file_name" : "AP_sanger_report_200423_2214.csv",
#   "file_name_date" : ISODate("2020-04-23T22:14:00Z"),
#   "created_at" : ISODate("2020-05-07T12:51:00Z"),
#   "updated_at" : ISODate("2020-08-17T15:15:32.048Z"),
#   "concat_id" : "GNM00015904 - AP-rna-00110029_F11 - Negative",
#   "migrated_temp" : "Yes"
# }